const KEY="mesVehiculesV1";
const EMPTY={vehicles:[],maintenance:[],cleaning:[],expenses:[],invoices:[],deadlines:[]};
let db=loadDB();

function loadDB(){try{const raw=localStorage.getItem(KEY);const parsed=raw?JSON.parse(raw):{};return {...EMPTY,...parsed};}catch(e){return {...EMPTY};}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(db));return true}catch(e){toast("Stockage presque plein : supprime quelques anciennes factures/photos.");return false;}}
function save(){if(persist()) render();}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function euro(n){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(Number(n)||0)}
function dateFR(s){if(!s)return "";const d=new Date(s+"T00:00:00");return Number.isNaN(d.getTime())?"":d.toLocaleDateString("fr-FR")}
function today(){return new Date().toISOString().slice(0,10)}
function uid(p){return p+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function vehicleName(id){const v=db.vehicles.find(x=>x.id===id);return v?`${v.marque||""} ${v.modele||""}${v.immat?` (${v.immat})`:""}`.trim():"Véhicule supprimé"}
function days(s){if(!s)return 99999;const d=new Date(s+"T00:00:00");const t=new Date();t.setHours(0,0,0,0);return Math.ceil((d-t)/86400000)}
function badge(s){const d=days(s);return d<0?'<span class="status urgent">🔴 Dépassé</span>':d<=30?'<span class="status soon">🟠 À prévoir</span>':'<span class="status ok">🟢 OK</span>'}
function toast(msg){const old=document.querySelector(".toast");if(old)old.remove();const el=document.createElement("div");el.className="toast";el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}

function switchTab(id){const target=document.getElementById(id);if(!target)return;document.querySelectorAll(".tab").forEach(s=>s.classList.remove("active"));target.classList.add("active");document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));window.scrollTo({top:0,behavior:"smooth"});render()}

document.addEventListener("click",e=>{
 const tab=e.target.closest("[data-tab]");if(tab){e.preventDefault();switchTab(tab.dataset.tab);return;}
 const action=e.target.closest("[data-action]");if(action){e.preventDefault();const a=action.dataset.action;({vehicle:openVehicle,maintenance:openMaintenance,cleaning:openCleaning,expense:openExpense,invoice:openInvoice,deadline:openDeadline,close:closeModal})[a]?.();}
});

document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
function modal(html){const m=document.getElementById("modal");document.getElementById("modalContent").innerHTML=html;m.classList.add("show");m.setAttribute("aria-hidden","false");setTimeout(()=>document.querySelector("#modalContent input, #modalContent select, #modalContent textarea")?.focus(),50)}
function closeModal(){const m=document.getElementById("modal");m.classList.remove("show");m.setAttribute("aria-hidden","true");document.getElementById("modalContent").innerHTML=""}
function selectVehicles(selected=""){return `<select id="vehicle" required><option value="">Choisir…</option>${db.vehicles.map(v=>`<option value="${esc(v.id)}" ${v.id===selected?"selected":""}>${esc(`${v.marque||""} ${v.modele||""} — ${v.immat||""}`)}</option>`).join("")}</select>`}

function openVehicle(){modal(`<h2>Ajouter un véhicule</h2><div class="form"><div class="two"><label>Marque<input id="marque" required></label><label>Modèle<input id="modele" required></label></div><div class="two"><label>Version<input id="version"></label><label>Immatriculation<input id="immat"></label></div><div class="two"><label>VIN<input id="vin"></label><label>Année<input id="annee" type="number" inputmode="numeric"></label></div><div class="two"><label>Kilométrage actuel<input id="km" type="number" inputmode="numeric"></label><label>Carburant<select id="fuel"><option>Diesel</option><option>Essence</option><option>Hybride</option><option>Électrique</option><option>GPL</option></select></label></div><div class="two"><label>Mise en circulation<input id="mise" type="date"></label><label>Échéance assurance<input id="assurance" type="date"></label></div><div class="two"><label>Échéance CT<input id="ct" type="date"></label><label>Nettoyage intérieur (jours)<input id="intfreq" type="number" value="30"></label></div><label>Nettoyage extérieur (jours)<input id="extfreq" type="number" value="14"></label><label>Notes<textarea id="notes"></textarea></label><button data-form="vehicle">Enregistrer</button></div>`)}
function addVehicle(){const g=id=>document.getElementById(id);if(!g("marque").value.trim()||!g("modele").value.trim()){toast("Renseigne au moins la marque et le modèle.");return}db.vehicles.push({id:uid("V"),marque:g("marque").value.trim(),modele:g("modele").value.trim(),version:g("version").value,immat:g("immat").value,vin:g("vin").value,annee:g("annee").value,mise:g("mise").value,km:Number(g("km").value)||0,fuel:g("fuel").value,assurance:g("assurance").value,ct:g("ct").value,intfreq:Number(g("intfreq").value)||30,extfreq:Number(g("extfreq").value)||14,notes:g("notes").value});save();closeModal();switchTab("vehicles")}

function openMaintenance(){modal(`<h2>Nouvel entretien</h2><div class="form"><label>Véhicule${selectVehicles()}</label><div class="two"><label>Date<input id="date" type="date" value="${today()}"></label><label>Kilométrage<input id="km" type="number" inputmode="numeric"></label></div><label>Type<select id="type"><option>Vidange</option><option>Freins</option><option>Distribution</option><option>Pneus</option><option>Batterie</option><option>Embrayage</option><option>Amortisseurs</option><option>Climatisation</option><option>Filtre</option><option>Autre</option></select></label><label>Travaux réalisés<textarea id="desc"></textarea></label><div class="two"><label>Pièces TTC<input id="parts" type="number" step="0.01" inputmode="decimal"></label><label>Main-d'œuvre TTC<input id="labor" type="number" step="0.01" inputmode="decimal"></label></div><div class="two"><label>Prochain km<input id="nextkm" type="number" inputmode="numeric"></label><label>Prochaine date<input id="nextdate" type="date"></label></div><button data-form="maintenance">Enregistrer</button></div>`)}
function addMaintenance(){const g=id=>document.getElementById(id);if(!g("vehicle").value||!g("date").value){toast("Choisis un véhicule et une date.");return}db.maintenance.push({id:uid("E"),vehicle:g("vehicle").value,date:g("date").value,km:Number(g("km").value)||0,type:g("type").value,desc:g("desc").value,parts:Number(g("parts").value)||0,labor:Number(g("labor").value)||0,nextkm:Number(g("nextkm").value)||0,nextdate:g("nextdate").value});save();closeModal();switchTab("maintenance")}

function openCleaning(){modal(`<h2>🧽 Nouveau nettoyage</h2><div class="form"><label>Véhicule${selectVehicles()}</label><div class="two"><label>Date<input id="date" type="date" value="${today()}"></label><label>Kilométrage<input id="km" type="number" inputmode="numeric"></label></div><label>Type<select id="type"><option>Intérieur</option><option>Extérieur</option><option>Intérieur + extérieur</option><option>Nettoyage approfondi</option><option>Shampoing sièges</option><option>Polissage / lustrage</option></select></label><div class="two"><label>Durée (min)<input id="duration" type="number" inputmode="numeric"></label><label>Coût TTC<input id="cost" type="number" step="0.01" inputmode="decimal"></label></div><label>Fréquence prévue (jours)<input id="freq" type="number" value="30" inputmode="numeric"></label><label>Notes<textarea id="notes"></textarea></label><button data-form="cleaning">Enregistrer</button></div>`)}
function addCleaning(){const g=id=>document.getElementById(id);db.cleaning.push({id:uid("N"),vehicle:g("vehicle").value,date:g("date").value,km:Number(g("km").value)||0,type:g("type").value,duration:Number(g("duration").value)||0,cost:Number(g("cost").value)||0,freq:Number(g("freq").value)||30,notes:g("notes").value});save();closeModal();switchTab("cleaning")}

function openExpense(){modal(`<h2>💶 Nouvelle dépense</h2><div class="form"><label>Véhicule${selectVehicles()}</label><div class="two"><label>Date<input id="date" type="date" value="${today()}"></label><label>Kilométrage<input id="km" type="number" inputmode="numeric"></label></div><label>Catégorie<select id="cat"><option>Carburant</option><option>Réparation</option><option>Entretien</option><option>Pneus</option><option>Assurance</option><option>Nettoyage</option><option>Parking</option><option>Péage</option><option>Autre</option></select></label><label>Description<textarea id="desc"></textarea></label><label>Montant TTC<input id="cost" type="number" step="0.01" inputmode="decimal"></label><button data-form="expense">Enregistrer</button></div>`)}
function addExpense(){const g=id=>document.getElementById(id);db.expenses.push({id:uid("D"),vehicle:g("vehicle").value,date:g("date").value,km:Number(g("km").value)||0,cat:g("cat").value,desc:g("desc").value,cost:Number(g("cost").value)||0});save();closeModal();switchTab("expenses")}

function openInvoice(){modal(`<h2>📄 Nouvelle facture numérisée</h2><div class="form"><label>Véhicule${selectVehicles()}</label><div class="two"><label>Date<input id="date" type="date" value="${today()}"></label><label>Montant TTC<input id="cost" type="number" step="0.01" inputmode="decimal"></label></div><label>Catégorie<select id="cat"><option>Facture entretien</option><option>Facture réparation</option><option>Pneus</option><option>Carburant</option><option>Assurance</option><option>Autre</option></select></label><label>Fournisseur<input id="supplier"></label><label>PDF / photo<input id="file" type="file" accept="image/*,application/pdf"></label><button data-form="invoice">Enregistrer la facture</button></div>`)}
async function addInvoice(){const g=id=>document.getElementById(id),file=g("file").files[0];let data="";if(file){if(file.size>8*1024*1024){toast("Fichier trop volumineux. Maximum 8 Mo.");return}data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}db.invoices.push({id:uid("FAC"),vehicle:g("vehicle").value,date:g("date").value,cost:Number(g("cost").value)||0,cat:g("cat").value,supplier:g("supplier").value,fileName:file?.name||"",data});save();closeModal();switchTab("invoices")}

function openDeadline(){modal(`<h2>📅 Nouvelle échéance</h2><div class="form"><label>Véhicule${selectVehicles()}</label><label>Type<select id="type"><option>Contrôle technique</option><option>Assurance</option><option>Garantie</option><option>Autre</option></select></label><label>Date échéance<input id="date" type="date"></label><label>Notes<textarea id="notes"></textarea></label><button data-form="deadline">Enregistrer</button></div>`)}
function addDeadline(){const g=id=>document.getElementById(id);if(!g("vehicle").value||!g("date").value){toast("Choisis un véhicule et une date.");return}db.deadlines.push({id:uid("EC"),vehicle:g("vehicle").value,type:g("type").value,date:g("date").value,notes:g("notes").value});save();closeModal();switchTab("deadlines")}

document.addEventListener("click",e=>{const b=e.target.closest("[data-form]");if(!b)return;const f=b.dataset.form;({vehicle:addVehicle,maintenance:addMaintenance,cleaning:addCleaning,expense:addExpense,invoice:addInvoice,deadline:addDeadline})[f]?.()});
function remove(arr,id){if(confirm("Supprimer cette entrée ?")){db[arr]=db[arr].filter(x=>x.id!==id);save()}}

function render(){
 document.getElementById("mVehicles").textContent=db.vehicles.length;
 const total=[...db.maintenance,...db.cleaning,...db.expenses].reduce((s,x)=>s+(Number(x.parts)||0)+(Number(x.labor)||0)+(Number(x.cost)||0),0);document.getElementById("mCosts").textContent=euro(total);
 const alerts=[];db.vehicles.forEach(v=>{if(v.assurance&&days(v.assurance)<=30)alerts.push({v,type:"Assurance",date:v.assurance});if(v.ct&&days(v.ct)<=30)alerts.push({v,type:"Contrôle technique",date:v.ct})});db.maintenance.forEach(x=>{if(x.nextdate&&days(x.nextdate)<=30)alerts.push({v:db.vehicles.find(v=>v.id===x.vehicle),type:"Entretien "+x.type,date:x.nextdate})});db.deadlines.forEach(x=>{if(x.date&&days(x.date)<=30)alerts.push({v:db.vehicles.find(v=>v.id===x.vehicle),type:x.type,date:x.date})});
 document.getElementById("mAlerts").textContent=alerts.length;document.getElementById("mMaint").textContent=db.maintenance.length;
 document.getElementById("alerts").innerHTML=alerts.length?alerts.filter(x=>x.v).sort((a,b)=>days(a.date)-days(b.date)).map(x=>`<div class="row"><div><b>${esc(x.v.marque)} ${esc(x.v.modele)}</b><p>${esc(x.type)} — ${dateFR(x.date)}</p></div><div>${badge(x.date)}</div></div>`).join(""):'<div class="empty">Aucune alerte 👍</div>';
 document.getElementById("recent").innerHTML=db.maintenance.slice().sort((a,b)=>(b.date||"").localeCompare(a.date||"")).slice(0,5).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} — ${esc(x.type)} — ${euro((x.parts||0)+(x.labor||0))}</p></div></div>`).join("")||'<div class="empty">Aucun entretien.</div>';
 document.getElementById("vehicleList").innerHTML=db.vehicles.map(v=>`<div class="vehicle"><h3>🚗 ${esc(v.marque)} ${esc(v.modele)}</h3><p><b>${esc(v.immat||"Sans immatriculation")}</b> • ${esc(v.km||0)} km</p><p>${esc(v.version||"")} • ${esc(v.fuel||"")}</p><p>Assurance : ${v.assurance?badge(v.assurance):"⚪ non renseignée"}<br>CT : ${v.ct?badge(v.ct):"⚪ non renseigné"}</p><div class="actions"><button class="danger" data-remove="vehicles" data-id="${esc(v.id)}">🗑️ Supprimer</button></div></div>`).join("")||'<div class="empty">Ajoute ton premier véhicule.</div>';
 document.getElementById("maintenanceList").innerHTML=db.maintenance.slice().sort((a,b)=>(b.date||"").localeCompare(a.date||"")).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} • ${esc(x.type)} • ${x.km||0} km</p><p>${esc(x.desc||"")} — ${euro((x.parts||0)+(x.labor||0))}</p>${x.nextdate?`<p>Prochaine date : ${dateFR(x.nextdate)} ${badge(x.nextdate)}</p>`:""}</div><div class="actions"><button data-remove="maintenance" data-id="${esc(x.id)}">🗑️</button></div></div>`).join("")||'<div class="empty">Aucun entretien.</div>';
 document.getElementById("cleaningList").innerHTML=db.cleaning.slice().sort((a,b)=>(b.date||"").localeCompare(a.date||"")).map(x=>{let n=x.freq?new Date(x.date+"T00:00:00"):null;if(n)n.setDate(n.getDate()+Number(x.freq));const nd=n&&!Number.isNaN(n.getTime())?n.toISOString().slice(0,10):"";return `<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} • ${esc(x.type)} • ${euro(x.cost)}</p><p>Prochain nettoyage : ${nd?dateFR(nd):"non programmé"} ${nd?badge(nd):""}</p></div><div class="actions"><button data-remove="cleaning" data-id="${esc(x.id)}">🗑️</button></div></div>`}).join("")||'<div class="empty">Aucun nettoyage.</div>';
 document.getElementById("expenseList").innerHTML=db.expenses.slice().sort((a,b)=>(b.date||"").localeCompare(a.date||"")).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} • ${esc(x.cat)} • ${euro(x.cost)}</p><p>${esc(x.desc||"")}</p></div><div class="actions"><button data-remove="expenses" data-id="${esc(x.id)}">🗑️</button></div></div>`).join("")||'<div class="empty">Aucune dépense.</div>';
 document.getElementById("invoiceList").innerHTML=db.invoices.slice().sort((a,b)=>(b.date||"").localeCompare(a.date||"")).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} • ${esc(x.cat)} • ${euro(x.cost)}</p><p>${esc(x.supplier||"")} ${esc(x.fileName||"")}</p>${x.data?`<a class="filelink" href="${x.data}" target="_blank" rel="noopener">📎 Ouvrir la facture</a>`:""}</div><div class="actions"><button data-remove="invoices" data-id="${esc(x.id)}">🗑️</button></div></div>`).join("")||'<div class="empty">Aucune facture numérisée.</div>';
 document.getElementById("deadlineList").innerHTML=db.deadlines.slice().sort((a,b)=>(a.date||"").localeCompare(b.date||"")).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${esc(x.type)} — ${dateFR(x.date)}</p><p>${esc(x.notes||"")}</p></div><div>${badge(x.date)} <button data-remove="deadlines" data-id="${esc(x.id)}">🗑️</button></div></div>`).join("")||'<div class="empty">Aucune échéance.</div>';
}

document.addEventListener("click",e=>{const b=e.target.closest("[data-remove]");if(b){e.preventDefault();remove(b.dataset.remove,b.dataset.id)}});
render();
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}))}
