const KEY="mesVehiculesV1";
let db=JSON.parse(localStorage.getItem(KEY)||'{"vehicles":[],"maintenance":[],"cleaning":[],"expenses":[],"invoices":[],"deadlines":[]}');
const save=()=>{localStorage.setItem(KEY,JSON.stringify(db));render()};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const euro=n=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(Number(n)||0);
const dateFR=s=>s?new Date(s+"T00:00:00").toLocaleDateString("fr-FR"):"";
const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,5);
const vehicleName=id=>{let v=db.vehicles.find(x=>x.id===id);return v?v.marque+" "+v.modele+" ("+v.immat+")":"Véhicule supprimé"};
function tabs(){document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active");render()})} tabs();
function modal(html){document.getElementById("modalContent").innerHTML=html;document.getElementById("modal").classList.add("show")}
function closeModal(){document.getElementById("modal").classList.remove("show")}
function selectVehicles(selected=""){return `<select id="vehicle" required><option value="">Choisir…</option>${db.vehicles.map(v=>`<option value="${v.id}" ${v.id===selected?"selected":""}>${esc(v.marque+" "+v.modele+" — "+v.immat)}</option>`).join("")}</select>`}
function openVehicle(){
modal(`<h2>Ajouter un véhicule</h2><div class="form"><div class="two"><label>Marque<input id="marque" required></label><label>Modèle<input id="modele" required></label></div><div class="two"><label>Version<input id="version"></label><label>Immatriculation<input id="immat"></label></div><div class="two"><label>VIN<input id="vin"></label><label>Année<input id="annee" type="number"></label></div><div class="two"><label>Kilométrage actuel<input id="km" type="number"></label><label>Carburant<select id="fuel"><option>Diesel</option><option>Essence</option><option>Hybride</option><option>Électrique</option><option>GPL</option></select></label></div><div class="two"><label>Mise en circulation<input id="mise" type="date"></label><label>Échéance assurance<input id="assurance" type="date"></label></div><div class="two"><label>Échéance CT<input id="ct" type="date"></label><label>Nettoyage intérieur (jours)<input id="intfreq" type="number" value="30"></label></div><label>Nettoyage extérieur (jours)<input id="extfreq" type="number" value="14"></label><label>Notes<textarea id="notes"></textarea></label><button onclick="addVehicle()">Enregistrer</button></div>`);
}
function addVehicle(){db.vehicles.push({id:uid("V"),marque:marque.value,modele:modele.value,version:version.value,immat:immat.value,vin:vin.value,annee:annee.value, mise:mise.value,km:+km.value,fuel:fuel.value,assurance:assurance.value,ct:ct.value,intfreq:+intfreq.value,extfreq:+extfreq.value,notes:notes.value});save();closeModal()}
function openMaintenance(){modal(`<h2>Nouvel entretien</h2><div class="form"><label>Véhicule${selectVehicles()}</label><div class="two"><label>Date<input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Kilométrage<input id="km" type="number"></label></div><label>Type<select id="type"><option>Vidange</option><option>Freins</option><option>Distribution</option><option>Pneus</option><option>Batterie</option><option>Embrayage</option><option>Amortisseurs</option><option>Climatisation</option><option>Filtre</option><option>Autre</option></select></label><label>Travaux réalisés<textarea id="desc"></textarea></label><div class="two"><label>Pièces TTC<input id="parts" type="number" step=".01"></label><label>Main-d'œuvre TTC<input id="labor" type="number" step=".01"></label></div><div class="two"><label>Prochain km<input id="nextkm" type="number"></label><label>Prochaine date<input id="nextdate" type="date"></label></div><button onclick="addMaintenance()">Enregistrer</button></div>`)}
function addMaintenance(){db.maintenance.push({id:uid("E"),vehicle:vehicle.value,date:date.value,km:+km.value,type:type.value,desc:desc.value,parts:+parts.value,labor:+labor.value,nextkm:+nextkm.value,nextdate:nextdate.value});save();closeModal()}
function openCleaning(){modal(`<h2>🧽 Nouveau nettoyage</h2><div class="form"><label>Véhicule${selectVehicles()}</label><div class="two"><label>Date<input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Kilométrage<input id="km" type="number"></label></div><label>Type<select id="type"><option>Intérieur</option><option>Extérieur</option><option>Intérieur + extérieur</option><option>Nettoyage approfondi</option><option>Shampoing sièges</option><option>Polissage / lustrage</option></select></label><div class="two"><label>Durée (min)<input id="duration" type="number"></label><label>Coût TTC<input id="cost" type="number" step=".01"></label></div><label>Fréquence prévue (jours)<input id="freq" type="number" value="30"></label><label>Notes<textarea id="notes"></textarea></label><button onclick="addCleaning()">Enregistrer</button></div>`)}
function addCleaning(){db.cleaning.push({id:uid("N"),vehicle:vehicle.value,date:date.value,km:+km.value,type:type.value,duration:+duration.value,cost:+cost.value,freq:+freq.value,notes:notes.value});save();closeModal()}
function openExpense(){modal(`<h2>💶 Nouvelle dépense</h2><div class="form"><label>Véhicule${selectVehicles()}</label><div class="two"><label>Date<input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Kilométrage<input id="km" type="number"></label></div><label>Catégorie<select id="cat"><option>Carburant</option><option>Réparation</option><option>Entretien</option><option>Pneus</option><option>Assurance</option><option>Nettoyage</option><option>Parking</option><option>Péage</option><option>Autre</option></select></label><label>Description<textarea id="desc"></textarea></label><label>Montant TTC<input id="cost" type="number" step=".01"></label><button onclick="addExpense()">Enregistrer</button></div>`)}
function addExpense(){db.expenses.push({id:uid("D"),vehicle:vehicle.value,date:date.value,km:+km.value,cat:cat.value,desc:desc.value,cost:+cost.value});save();closeModal()}
function openInvoice(){modal(`<h2>📄 Nouvelle facture numérisée</h2><div class="form"><label>Véhicule${selectVehicles()}</label><div class="two"><label>Date<input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Montant TTC<input id="cost" type="number" step=".01"></label></div><label>Catégorie<select id="cat"><option>Facture entretien</option><option>Facture réparation</option><option>Pneus</option><option>Carburant</option><option>Assurance</option><option>Autre</option></select></label><label>Fournisseur<input id="supplier"></label><label>Numérisation (PDF / photo)<input id="file" type="file" accept="image/*,application/pdf"></label><button onclick="addInvoice()">Enregistrer la facture</button></div>`)}
async function addInvoice(){let file=document.getElementById("file").files[0];let data="";if(file){data=await new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}db.invoices.push({id:uid("FAC"),vehicle:vehicle.value,date:date.value,cost:+cost.value,cat:cat.value,supplier:supplier.value,fileName:file?.name||"",data});save();closeModal()}
function openDeadline(){modal(`<h2>📅 Nouvelle échéance</h2><div class="form"><label>Véhicule${selectVehicles()}</label><label>Type<select id="type"><option>Contrôle technique</option><option>Assurance</option><option>Garantie</option><option>Autre</option></select></label><label>Date échéance<input id="date" type="date"></label><label>Notes<textarea id="notes"></textarea></label><button onclick="addDeadline()">Enregistrer</button></div>`)}
function addDeadline(){db.deadlines.push({id:uid("EC"),vehicle:vehicle.value,type:type.value,date:date.value,notes:notes.value});save();closeModal()}
function days(s){return s?Math.ceil((new Date(s+"T00:00:00")-new Date(new Date().toDateString()))/86400000):99999}
function badge(s){let d=days(s);return d<0?'<span class="status urgent">🔴 Dépassé</span>':d<=30?'<span class="status soon">🟠 À prévoir</span>':'<span class="status ok">🟢 OK</span>'}
function remove(arr,id){if(confirm("Supprimer cette entrée ?")){db[arr]=db[arr].filter(x=>x.id!==id);save()}}
function render(){
  document.getElementById("mVehicles").textContent=db.vehicles.length;
  let total=[...db.maintenance,...db.cleaning,...db.expenses].reduce((s,x)=>s+(x.parts||0)+(x.labor||0)+(x.cost||0),0);
  document.getElementById("mCosts").textContent=euro(total);
  let alerts=[];
  db.vehicles.forEach(v=>{if(days(v.assurance)<=30)alerts.push({v,type:"Assurance",date:v.assurance});if(days(v.ct)<=30)alerts.push({v,type:"Contrôle technique",date:v.ct})});
  db.maintenance.forEach(x=>{if(x.nextdate&&days(x.nextdate)<=30)alerts.push({v:db.vehicles.find(v=>v.id===x.vehicle),type:"Entretien "+x.type,date:x.nextdate})});
  db.cleaning.forEach(x=>{let n=x.freq?new Date(x.date+"T00:00:00");n.setDate(n.getDate()+x.freq);let d=n.toISOString().slice(0,10);if(days(d)<=7)alerts.push({v:db.vehicles.find(v=>v.id===x.vehicle),type:"Nettoyage "+x.type,date:d})});
  document.getElementById("mAlerts").textContent=alerts.length; document.getElementById("mMaint").textContent=db.maintenance.length;
  document.getElementById("alerts").innerHTML=alerts.length?alerts.sort((a,b)=>days(a.date)-days(b.date)).map(x=>`<div class="row"><div><b>${esc(x.v?.marque||"") } ${esc(x.v?.modele||"")}</b><p>${esc(x.type)} — ${dateFR(x.date)}</p></div><div>${badge(x.date)}</div></div>`).join(""):'<div class="empty">Aucune alerte 👍</div>';
  document.getElementById("recent").innerHTML=db.maintenance.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} — ${esc(x.type)} — ${euro((x.parts||0)+(x.labor||0))}</p></div></div>`).join("")||'<div class="empty">Aucun entretien.</div>';
  document.getElementById("vehicleList").innerHTML=db.vehicles.map(v=>`<div class="vehicle"><h3>🚗 ${esc(v.marque)} ${esc(v.modele)}</h3><p><b>${esc(v.immat)}</b> • ${esc(v.km||0)} km</p><p>${esc(v.version||"")} • ${esc(v.fuel||"")}</p><p>Assurance : ${v.assurance?badge(v.assurance):"⚪ non renseignée"}<br>CT : ${v.ct?badge(v.ct):"⚪ non renseigné"}</p><button class="actions" onclick="remove('vehicles','${v.id}')">🗑️ Supprimer</button></div>`).join("")||'<div class="empty">Ajoute ton premier véhicule.</div>';
  document.getElementById("maintenanceList").innerHTML=db.maintenance.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} • ${esc(x.type)} • ${x.km||0} km</p><p>${esc(x.desc||"")} — ${euro((x.parts||0)+(x.labor||0))}</p>${x.nextdate?`<p>Prochaine date : ${dateFR(x.nextdate)} ${badge(x.nextdate)}</p>`:""}</div><div class="actions"><button onclick="remove('maintenance','${x.id}')">🗑️</button></div></div>`).join("")||'<div class="empty">Aucun entretien.</div>';
  document.getElementById("cleaningList").innerHTML=db.cleaning.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>{let n=x.freq?new Date(x.date+"T00:00:00"):null;if(n)n.setDate(n.getDate()+x.freq);let nd=n?n.toISOString().slice(0,10):"";return `<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} • ${esc(x.type)} • ${euro(x.cost)}</p><p>Prochain nettoyage : ${nd?dateFR(nd):"non programmé"} ${nd?badge(nd):""}</p></div><button onclick="remove('cleaning','${x.id}')">🗑️</button></div>`}).join("")||'<div class="empty">Aucun nettoyage.</div>';
  document.getElementById("expenseList").innerHTML=db.expenses.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} • ${esc(x.cat)} • ${euro(x.cost)}</p><p>${esc(x.desc||"")}</p></div><button onclick="remove('expenses','${x.id}')">🗑️</button></div>`).join("")||'<div class="empty">Aucune dépense.</div>';
  document.getElementById("invoiceList").innerHTML=db.invoices.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${dateFR(x.date)} • ${esc(x.cat)} • ${euro(x.cost)}</p><p>${esc(x.supplier||"")} ${esc(x.fileName||"")}</p>${x.data?`<a class="filelink" href="${x.data}" target="_blank">📎 Ouvrir la facture</a>`:""}</div><button onclick="remove('invoices','${x.id}')">🗑️</button></div>`).join("")||'<div class="empty">Aucune facture numérisée.</div>';
  document.getElementById("deadlineList").innerHTML=db.deadlines.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<div class="row"><div><b>${esc(vehicleName(x.vehicle))}</b><p>${esc(x.type)} — ${dateFR(x.date)}</p><p>${esc(x.notes||"")}</p></div><div>${badge(x.date)} <button onclick="remove('deadlines','${x.id}')">🗑️</button></div></div>`).join("")||'<div class="empty">Aucune échéance.</div>';
}
render();
if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js");
